#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ICT638July2020Group1Android.Resource", IsApplication=true)]

namespace ICT638July2020Group1Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.alpha = global::ICT638July2020Group1Android.Resource.Attribute.alpha;
			global::Xamarin.Essentials.Resource.Attribute.coordinatorLayoutStyle = global::ICT638July2020Group1Android.Resource.Attribute.coordinatorLayoutStyle;
			global::Xamarin.Essentials.Resource.Attribute.font = global::ICT638July2020Group1Android.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::ICT638July2020Group1Android.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::ICT638July2020Group1Android.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::ICT638July2020Group1Android.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::ICT638July2020Group1Android.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::ICT638July2020Group1Android.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::ICT638July2020Group1Android.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::ICT638July2020Group1Android.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontVariationSettings = global::ICT638July2020Group1Android.Resource.Attribute.fontVariationSettings;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::ICT638July2020Group1Android.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Attribute.keylines = global::ICT638July2020Group1Android.Resource.Attribute.keylines;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchor = global::ICT638July2020Group1Android.Resource.Attribute.layout_anchor;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchorGravity = global::ICT638July2020Group1Android.Resource.Attribute.layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Attribute.layout_behavior = global::ICT638July2020Group1Android.Resource.Attribute.layout_behavior;
			global::Xamarin.Essentials.Resource.Attribute.layout_dodgeInsetEdges = global::ICT638July2020Group1Android.Resource.Attribute.layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Attribute.layout_insetEdge = global::ICT638July2020Group1Android.Resource.Attribute.layout_insetEdge;
			global::Xamarin.Essentials.Resource.Attribute.layout_keyline = global::ICT638July2020Group1Android.Resource.Attribute.layout_keyline;
			global::Xamarin.Essentials.Resource.Attribute.statusBarBackground = global::ICT638July2020Group1Android.Resource.Attribute.statusBarBackground;
			global::Xamarin.Essentials.Resource.Attribute.ttcIndex = global::ICT638July2020Group1Android.Resource.Attribute.ttcIndex;
			global::Xamarin.Essentials.Resource.Color.browser_actions_bg_grey = global::ICT638July2020Group1Android.Resource.Color.browser_actions_bg_grey;
			global::Xamarin.Essentials.Resource.Color.browser_actions_divider_color = global::ICT638July2020Group1Android.Resource.Color.browser_actions_divider_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_text_color = global::ICT638July2020Group1Android.Resource.Color.browser_actions_text_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_title_color = global::ICT638July2020Group1Android.Resource.Color.browser_actions_title_color;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::ICT638July2020Group1Android.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::ICT638July2020Group1Android.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Color.ripple_material_light = global::ICT638July2020Group1Android.Resource.Color.ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.secondary_text_default_material_light = global::ICT638July2020Group1Android.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_max_width = global::ICT638July2020Group1Android.Resource.Dimension.browser_actions_context_menu_max_width;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_min_padding = global::ICT638July2020Group1Android.Resource.Dimension.browser_actions_context_menu_min_padding;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::ICT638July2020Group1Android.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::ICT638July2020Group1Android.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::ICT638July2020Group1Android.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::ICT638July2020Group1Android.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::ICT638July2020Group1Android.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_height = global::ICT638July2020Group1Android.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_width = global::ICT638July2020Group1Android.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::ICT638July2020Group1Android.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::ICT638July2020Group1Android.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::ICT638July2020Group1Android.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::ICT638July2020Group1Android.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::ICT638July2020Group1Android.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::ICT638July2020Group1Android.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::ICT638July2020Group1Android.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::ICT638July2020Group1Android.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::ICT638July2020Group1Android.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::ICT638July2020Group1Android.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::ICT638July2020Group1Android.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::ICT638July2020Group1Android.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::ICT638July2020Group1Android.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::ICT638July2020Group1Android.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::ICT638July2020Group1Android.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::ICT638July2020Group1Android.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::ICT638July2020Group1Android.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::ICT638July2020Group1Android.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::ICT638July2020Group1Android.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::ICT638July2020Group1Android.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::ICT638July2020Group1Android.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::ICT638July2020Group1Android.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::ICT638July2020Group1Android.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::ICT638July2020Group1Android.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::ICT638July2020Group1Android.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::ICT638July2020Group1Android.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::ICT638July2020Group1Android.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.action_container = global::ICT638July2020Group1Android.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::ICT638July2020Group1Android.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::ICT638July2020Group1Android.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::ICT638July2020Group1Android.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.actions = global::ICT638July2020Group1Android.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.all = global::ICT638July2020Group1Android.Resource.Id.all;
			global::Xamarin.Essentials.Resource.Id.async = global::ICT638July2020Group1Android.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::ICT638July2020Group1Android.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.bottom = global::ICT638July2020Group1Android.Resource.Id.bottom;
			global::Xamarin.Essentials.Resource.Id.browser_actions_header_text = global::ICT638July2020Group1Android.Resource.Id.browser_actions_header_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_icon = global::ICT638July2020Group1Android.Resource.Id.browser_actions_menu_item_icon;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_text = global::ICT638July2020Group1Android.Resource.Id.browser_actions_menu_item_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_items = global::ICT638July2020Group1Android.Resource.Id.browser_actions_menu_items;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_view = global::ICT638July2020Group1Android.Resource.Id.browser_actions_menu_view;
			global::Xamarin.Essentials.Resource.Id.center = global::ICT638July2020Group1Android.Resource.Id.center;
			global::Xamarin.Essentials.Resource.Id.center_horizontal = global::ICT638July2020Group1Android.Resource.Id.center_horizontal;
			global::Xamarin.Essentials.Resource.Id.center_vertical = global::ICT638July2020Group1Android.Resource.Id.center_vertical;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::ICT638July2020Group1Android.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.clip_horizontal = global::ICT638July2020Group1Android.Resource.Id.clip_horizontal;
			global::Xamarin.Essentials.Resource.Id.clip_vertical = global::ICT638July2020Group1Android.Resource.Id.clip_vertical;
			global::Xamarin.Essentials.Resource.Id.end = global::ICT638July2020Group1Android.Resource.Id.end;
			global::Xamarin.Essentials.Resource.Id.fill = global::ICT638July2020Group1Android.Resource.Id.fill;
			global::Xamarin.Essentials.Resource.Id.fill_horizontal = global::ICT638July2020Group1Android.Resource.Id.fill_horizontal;
			global::Xamarin.Essentials.Resource.Id.fill_vertical = global::ICT638July2020Group1Android.Resource.Id.fill_vertical;
			global::Xamarin.Essentials.Resource.Id.forever = global::ICT638July2020Group1Android.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::ICT638July2020Group1Android.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::ICT638July2020Group1Android.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::ICT638July2020Group1Android.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::ICT638July2020Group1Android.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.left = global::ICT638July2020Group1Android.Resource.Id.left;
			global::Xamarin.Essentials.Resource.Id.line1 = global::ICT638July2020Group1Android.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::ICT638July2020Group1Android.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.none = global::ICT638July2020Group1Android.Resource.Id.none;
			global::Xamarin.Essentials.Resource.Id.normal = global::ICT638July2020Group1Android.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::ICT638July2020Group1Android.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::ICT638July2020Group1Android.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::ICT638July2020Group1Android.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right = global::ICT638July2020Group1Android.Resource.Id.right;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::ICT638July2020Group1Android.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::ICT638July2020Group1Android.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.start = global::ICT638July2020Group1Android.Resource.Id.start;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::ICT638July2020Group1Android.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_event_manager = global::ICT638July2020Group1Android.Resource.Id.tag_unhandled_key_event_manager;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_listeners = global::ICT638July2020Group1Android.Resource.Id.tag_unhandled_key_listeners;
			global::Xamarin.Essentials.Resource.Id.text = global::ICT638July2020Group1Android.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::ICT638July2020Group1Android.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::ICT638July2020Group1Android.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::ICT638July2020Group1Android.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Id.top = global::ICT638July2020Group1Android.Resource.Id.top;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::ICT638July2020Group1Android.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_page = global::ICT638July2020Group1Android.Resource.Layout.browser_actions_context_menu_page;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_row = global::ICT638July2020Group1Android.Resource.Layout.browser_actions_context_menu_row;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::ICT638July2020Group1Android.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::ICT638July2020Group1Android.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::ICT638July2020Group1Android.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::ICT638July2020Group1Android.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::ICT638July2020Group1Android.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::ICT638July2020Group1Android.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::ICT638July2020Group1Android.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::ICT638July2020Group1Android.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::ICT638July2020Group1Android.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::ICT638July2020Group1Android.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::ICT638July2020Group1Android.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::ICT638July2020Group1Android.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::ICT638July2020Group1Android.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::ICT638July2020Group1Android.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Style.Widget_Support_CoordinatorLayout = global::ICT638July2020Group1Android.Resource.Style.Widget_Support_CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::ICT638July2020Group1Android.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem = global::ICT638July2020Group1Android.Resource.Styleable.ColorStateListItem;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_alpha = global::ICT638July2020Group1Android.Resource.Styleable.ColorStateListItem_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_alpha = global::ICT638July2020Group1Android.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_color = global::ICT638July2020Group1Android.Resource.Styleable.ColorStateListItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout = global::ICT638July2020Group1Android.Resource.Styleable.CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_keylines = global::ICT638July2020Group1Android.Resource.Styleable.CoordinatorLayout_keylines;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_statusBarBackground = global::ICT638July2020Group1Android.Resource.Styleable.CoordinatorLayout_statusBarBackground;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout = global::ICT638July2020Group1Android.Resource.Styleable.CoordinatorLayout_Layout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity = global::ICT638July2020Group1Android.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor = global::ICT638July2020Group1Android.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity = global::ICT638July2020Group1Android.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior = global::ICT638July2020Group1Android.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges = global::ICT638July2020Group1Android.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge = global::ICT638July2020Group1Android.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline = global::ICT638July2020Group1Android.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::ICT638July2020Group1Android.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::ICT638July2020Group1Android.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::ICT638July2020Group1Android.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::ICT638July2020Group1Android.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::ICT638July2020Group1Android.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::ICT638July2020Group1Android.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::ICT638July2020Group1Android.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::ICT638July2020Group1Android.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::ICT638July2020Group1Android.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::ICT638July2020Group1Android.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::ICT638July2020Group1Android.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::ICT638July2020Group1Android.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::ICT638July2020Group1Android.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::ICT638July2020Group1Android.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::ICT638July2020Group1Android.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::ICT638July2020Group1Android.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::ICT638July2020Group1Android.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_ttcIndex = global::ICT638July2020Group1Android.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerColor = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_centerColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerX = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_centerX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerY = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_centerY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endColor = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_endColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endX = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_endX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endY = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_endY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_gradientRadius = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startColor = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_startColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startX = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_startX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startY = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_startY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_tileMode = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_tileMode;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_type = global::ICT638July2020Group1Android.Resource.Styleable.GradientColor_android_type;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem = global::ICT638July2020Group1Android.Resource.Styleable.GradientColorItem;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_color = global::ICT638July2020Group1Android.Resource.Styleable.GradientColorItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_offset = global::ICT638July2020Group1Android.Resource.Styleable.GradientColorItem_android_offset;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int abc_fade_in = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int abc_fade_out = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int abc_grow_fade_in_from_bottom = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int abc_popup_enter = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int abc_popup_exit = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int abc_shrink_fade_out_from_bottom = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int abc_slide_in_bottom = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int abc_slide_in_top = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int abc_slide_out_bottom = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int abc_slide_out_top = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int abc_tooltip_enter = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int abc_tooltip_exit = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int design_bottom_sheet_slide_in = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int design_bottom_sheet_slide_out = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int design_snackbar_in = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int design_snackbar_out = 2130771983;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public const int design_appbar_state_list_animator = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int design_fab_hide_motion_spec = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int design_fab_show_motion_spec = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int mtrl_btn_state_list_anim = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int mtrl_btn_unelevated_state_list_anim = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int mtrl_chip_state_list_anim = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int mtrl_fab_hide_motion_spec = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int mtrl_fab_show_motion_spec = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int mtrl_fab_transformation_sheet_collapse_spec = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int mtrl_fab_transformation_sheet_expand_spec = 2130837513;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int myButton = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F090000
			public const int abc_config_activityDefaultDur = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int abc_config_activityShortDur = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int app_bar_elevation_anim_duration = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int bottom_sheet_slide_duration = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int cancel_button_image_alpha = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int config_tooltipAnimTime = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int design_snackbar_text_max_lines = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int design_tab_indicator_anim_duration_ms = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int hide_password_duration = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int mtrl_btn_anim_delay_ms = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int mtrl_btn_anim_duration_ms = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int mtrl_chip_anim_duration = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int mtrl_tab_indicator_anim_duration_ms = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int show_password_duration = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int status_bar_notification_info_maxnum = 2131296270;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F0C0000
			public const int navigation = 2131492864;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7F0D0010
			public const int abc_font_family_headline_material = 2131558416;
			
			// aapt resource value: 0x7F0D0011
			public const int abc_font_family_menu_material = 2131558417;
			
			// aapt resource value: 0x7F0D0012
			public const int abc_font_family_subhead_material = 2131558418;
			
			// aapt resource value: 0x7F0D0013
			public const int abc_font_family_title_material = 2131558419;
			
			// aapt resource value: 0x7F0D0014
			public const int abc_menu_alt_shortcut_label = 2131558420;
			
			// aapt resource value: 0x7F0D0015
			public const int abc_menu_ctrl_shortcut_label = 2131558421;
			
			// aapt resource value: 0x7F0D0016
			public const int abc_menu_delete_shortcut_label = 2131558422;
			
			// aapt resource value: 0x7F0D0017
			public const int abc_menu_enter_shortcut_label = 2131558423;
			
			// aapt resource value: 0x7F0D0018
			public const int abc_menu_function_shortcut_label = 2131558424;
			
			// aapt resource value: 0x7F0D0019
			public const int abc_menu_meta_shortcut_label = 2131558425;
			
			// aapt resource value: 0x7F0D001A
			public const int abc_menu_shift_shortcut_label = 2131558426;
			
			// aapt resource value: 0x7F0D001B
			public const int abc_menu_space_shortcut_label = 2131558427;
			
			// aapt resource value: 0x7F0D001C
			public const int abc_menu_sym_shortcut_label = 2131558428;
			
			// aapt resource value: 0x7F0D001D
			public const int abc_prepend_shortcut_label = 2131558429;
			
			// aapt resource value: 0x7F0D001F
			public const int abc_searchview_description_clear = 2131558431;
			
			// aapt resource value: 0x7F0D0020
			public const int abc_searchview_description_query = 2131558432;
			
			// aapt resource value: 0x7F0D0021
			public const int abc_searchview_description_search = 2131558433;
			
			// aapt resource value: 0x7F0D0022
			public const int abc_searchview_description_submit = 2131558434;
			
			// aapt resource value: 0x7F0D0023
			public const int abc_searchview_description_voice = 2131558435;
			
			// aapt resource value: 0x7F0D001E
			public const int abc_search_hint = 2131558430;
			
			// aapt resource value: 0x7F0D0024
			public const int abc_shareactionprovider_share_with = 2131558436;
			
			// aapt resource value: 0x7F0D0025
			public const int abc_shareactionprovider_share_with_application = 2131558437;
			
			// aapt resource value: 0x7F0D0026
			public const int abc_toolbar_collapse_description = 2131558438;
			
			// aapt resource value: 0x7F0D0027
			public const int action_settings = 2131558439;
			
			// aapt resource value: 0x7F0D0029
			public const int appbar_scrolling_view_behavior = 2131558441;
			
			// aapt resource value: 0x7F0D0028
			public const int app_name = 2131558440;
			
			// aapt resource value: 0x7F0D002A
			public const int bottom_sheet_behavior = 2131558442;
			
			// aapt resource value: 0x7F0D002B
			public const int character_counter_content_description = 2131558443;
			
			// aapt resource value: 0x7F0D002C
			public const int character_counter_pattern = 2131558444;
			
			// aapt resource value: 0x7F0D002D
			public const int fab_transformation_scrim_behavior = 2131558445;
			
			// aapt resource value: 0x7F0D002E
			public const int fab_transformation_sheet_behavior = 2131558446;
			
			// aapt resource value: 0x7F0D002F
			public const int hide_bottom_view_on_scroll_behavior = 2131558447;
			
			// aapt resource value: 0x7F0D0030
			public const int mtrl_chip_close_icon_content_description = 2131558448;
			
			// aapt resource value: 0x7F0D0031
			public const int password_toggle_content_description = 2131558449;
			
			// aapt resource value: 0x7F0D0032
			public const int path_password_eye = 2131558450;
			
			// aapt resource value: 0x7F0D0033
			public const int path_password_eye_mask_strike_through = 2131558451;
			
			// aapt resource value: 0x7F0D0034
			public const int path_password_eye_mask_visible = 2131558452;
			
			// aapt resource value: 0x7F0D0035
			public const int path_password_strike_through = 2131558453;
			
			// aapt resource value: 0x7F0D0036
			public const int search_menu_title = 2131558454;
			
			// aapt resource value: 0x7F0D0037
			public const int status_bar_notification_info_overflow = 2131558455;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
